language: csharp
solution: ./src/serilog-sinks-graylog.sln
install:
  - curl -L -o nuget.exe https://dist.nuget.org/win-x86-commandline/latest/nuget.exe
  - mono nuget.exe restore ./src/serilog-sinks-graylog.sln -Verbosity detailed
script:
  - xbuild /p:Configuration=Release ./src/serilog-sinks-graylog.sln
