version: 1.0.{build}
skip_tags: true
assembly_info:
  patch: true
  file: AssemblyInfo.*
  assembly_version: "{version}"
  assembly_file_version: "{version}"
  assembly_informational_version: "{version}"
install:
  -nuget restore

Configuration: Release

build:
  project: ./src/serilog-sinks-graylog.sln
  verbosity: minimal

test:
  categories:
    except:
    - Integration
