-
  branches:
    except:
      - release
  init:
    - cmd: "set branch=%APPVEYOR_REPO_BRANCH%"
    - cmd: "echo branch:%branch%"
    - cmd: "set newVersion=1.0.%APPVEYOR_BUILD_NUMBER%-%branch%"
    - cmd: "echo newVersion:%newVersion%"
    - cmd: "set versonSuffix=%APPVEYOR_BUILD_NUMBER%-%branch%"    
    - cmd: "echo versonSuffix:%versonSuffix%"
    - cmd: appveyor UpdateBuild -Version "%newVersion%"

  skip_tags: true

  assembly_info:
    patch: true
    file: AssemblyInfo.*
    assembly_version: "{version}"
    assembly_file_version: "{version}"
    assembly_informational_version: "{version}"

  configuration: Release

  image: Visual Studio 2017 RC

  build_script:
    - cmd: dir
    - cmd: msbuild /t:restore /v:Minimal ./src/serilog-sinks-graylogvs2017.sln
    - cmd: msbuild /t:build /p:Configuration=Debug /v:Minimal ./src/serilog-sinks-graylogvs2017.sln
    - cmd: msbuild /t:pack /v:minimal /p:IncludeSymbols=true /p:PackageOutputPath=../../artifacts /p:PackageVersion=%newVersion% ./src/Serilog.Sinks.Graylog/Serilog.Sinks.Graylog.csproj

  test:
    categories:
      except:
        - Integration

  after_test:
    - .\packages\OpenCover\tools\OpenCover.Console.exe -register:user -target:"%xunit20%\xunit.console.x86.exe" -targetargs:".\src\Serilog.Sinks.Graylog.Tests\bin\Debug\net46\Serilog.Sinks.Graylog.Tests.dll -noshadow -appveyor" -filter:"+[Serilog.Sinks.Graylog*]* -[*]*Test*" -hideskipped:All -output:.\coverage.xml
    - "SET PATH=C:\\Python34;C:\\Python34\\Scripts;%PATH%"
    - pip install codecov
    - codecov -f "coverage.xml"
  
  artifacts:
    - path: "C:\\projects\\serilog-sinks-graylog\\artifacts\\*.*"
-
  branches:
    only:
      - release

  assembly_info:
    patch: true
    file: AssemblyInfo.*
    assembly_version: "{version}"
    assembly_file_version: "{version}"
    assembly_informational_version: "{version}"

  configuration: Release

  before_build:
    - appveyor-retry dotnet restore -v Minimal

  build_script:
    - cmd: dotnet build "./src/Serilog.Sinks.Graylog" -c %CONFIGURATION% --no-dependencies
  after_build:
    - cmd: dotnet pack "./src/Serilog.Sinks.Graylog" -c %CONFIGURATION% --no-build -o artifacts
  test_script:
    - cmd: dotnet test "./src/Serilog.Sinks.Graylog.Tests" -c %CONFIGURATION% -notrait "Category=Integration"
  
  artifacts:
    - path: "./artifacts/*.nupkg"

  deploy:
    provider: NuGet
    api_key:
      secure: IHVAasaX8yvwCHeCI/mBgWBRzLNlOpRn3yJnZFyslzTnJpELyxKDaKM5y/LN0zsl
      skip_symbols: false
      artifact: /.*\.nupkg/