-
  branches:
    except:
      - release
  init:
    - cmd: "set branch=%APPVEYOR_REPO_BRANCH%"
    - cmd: "echo branch:%branch%"
    - cmd: "set newVersion=1.0.%APPVEYOR_BUILD_NUMBER%-%branch%"
    - cmd: "echo newVersion:%newVersion%"
    - cmd: "set versonSuffix=%APPVEYOR_BUILD_NUMBER%-%branch%"    
    - cmd: "echo versonSuffix:%versonSuffix%"
    - cmd: appveyor UpdateBuild -Version "%newVersion%"

  skip_tags: true

  assembly_info:
    patch: true
    file: AssemblyInfo.*
    assembly_version: "{version}"
    assembly_file_version: "{version}"
    assembly_informational_version: "{version}"

  configuration: Release

  before_build:
    - appveyor-retry dotnet restore -v Minimal

  build_script:
    - cmd: dotnet build "./src/Serilog.Sinks.Graylog" -c %CONFIGURATION% --no-dependencies --version-suffix %APPVEYOR_BUILD_NUMBER%
  after_build:
    - cmd: dotnet pack "./src/Serilog.Sinks.Graylog" -c %CONFIGURATION% --no-build --version-suffix %APPVEYOR_BUILD_NUMBER% -o artifacts
  test_script:
    - cmd: dotnet test "./src/Serilog.Sinks.Graylog.Tests" -c %CONFIGURATION% -notrait "Category=Integration"
  
  artifacts:
    - path: "./artifacts/*.nupkg"

  deploy:
    provider: NuGet
    api_key:
      #secure: IHVAasaX8yvwCHeCI/mBgWBRzLNlOpRn3yJnZFyslzTnJpELyxKDaKM5y/LN0zsl
      skip_symbols: false
      artifact: /.*\.nupkg/
-
  branches:
    only:
      - release

  assembly_info:
    patch: true
    file: AssemblyInfo.*
    assembly_version: "{version}"
    assembly_file_version: "{version}"
    assembly_informational_version: "{version}"

  configuration: Release

  before_build:
    - appveyor-retry dotnet restore -v Minimal

  build_script:
    - cmd: dotnet build "./src/Serilog.Sinks.Graylog" -c %CONFIGURATION% --no-dependencies
  after_build:
    - cmd: dotnet pack "./src/Serilog.Sinks.Graylog" -c %CONFIGURATION% --no-build -o artifacts
  test_script:
    - cmd: dotnet test "./src/Serilog.Sinks.Graylog.Tests" -c %CONFIGURATION% -notrait "Category=Integration"
  
  artifacts:
    - path: "./artifacts/*.nupkg"

  deploy:
    provider: NuGet
    api_key:
      secure: IHVAasaX8yvwCHeCI/mBgWBRzLNlOpRn3yJnZFyslzTnJpELyxKDaKM5y/LN0zsl
      skip_symbols: false
      artifact: /.*\.nupkg/