-
  branches:
    except:
      - release
  init:
    - cmd: "set branch=%APPVEYOR_REPO_BRANCH%"
    - cmd: "echo branch:%branch%"
    - cmd: "set newVersion=1.0.%APPVEYOR_BUILD_NUMBER%-%branch%"
    - cmd: "echo newVersion:%newVersion%"
    - cmd: "set versonSuffix=%APPVEYOR_BUILD_NUMBER%-%branch%"    
    - cmd: "echo versonSuffix:%versonSuffix%"
    - cmd: appveyor UpdateBuild -Version "%newVersion%"

  skip_tags: true

  before_build:
    - nuget install OpenCover -ExcludeVersion -OutputDirectory "packages"

  assembly_info:
    patch: true
    file: AssemblyInfo.*
    assembly_version: "{version}"
    assembly_file_version: "{version}"
    assembly_informational_version: "{version}"

  configuration: Debug

  image: Visual Studio 2017

  build_script:
    - cmd: msbuild /t:restore /v:Minimal ./src/serilog-sinks-graylogvs2017.sln
    - cmd: msbuild /t:build /p:Configuration=Debug /v:Minimal ./src/serilog-sinks-graylogvs2017.sln
    - cmd: msbuild /t:pack /v:minimal /p:IncludeSymbols=true /p:PackageOutputPath=../../artifacts /p:PackageVersion=%newVersion% ./src/Serilog.Sinks.Graylog/Serilog.Sinks.Graylog.csproj

  test:
    categories:
      except:
        - Integration

  after_test:
    - cmd: "dir C:\\projects\\serilog-sinks-graylog\\src\\Serilog.Sinks.Graylog.Tests\\bin\\Debug\\net46"
    - .\packages\OpenCover\tools\OpenCover.Console.exe -register -target:"%xunit20%\xunit.console.x86.exe" -targetdir:"C:\projects\serilog-sinks-graylog\src\Serilog.Sinks.Graylog.Tests\bin\Debug\net46\" -targetargs:"Serilog.Sinks.Graylog.Tests.dll" -filter:"+[Serilog.Sinks.Graylog*]* -[*]*Test*" -output:.\coverage.xml
    - "SET PATH=C:\\Python34;C:\\Python34\\Scripts;%PATH%"
    - pip install codecov
    - codecov -f "coverage.xml" -X gcov
  
  artifacts:
    - path: "./artifacts/*.*"
-
  branches:
    only:
      - release

  assembly_info:
    patch: true
    file: AssemblyInfo.*
    assembly_version: "{version}"
    assembly_file_version: "{version}"
    assembly_informational_version: "{version}"

  configuration: Release

  image: Visual Studio 2017

  before_build:
    - appveyor-retry dotnet restore -v Minimal

  build_script:
    - cmd: msbuild /t:restore /v:Minimal ./src/serilog-sinks-graylogvs2017.sln
    - cmd: msbuild /t:build /p:Configuration=Debug /v:Minimal ./src/serilog-sinks-graylogvs2017.sln
    - cmd: msbuild /t:pack /v:minimal /p:IncludeSymbols=true /p:PackageOutputPath=../../artifacts ./src/Serilog.Sinks.Graylog/Serilog.Sinks.Graylog.csproj
  
  test:
    categories:
      except:
        - Integration
  
  artifacts:
    - path: "./artifacts/*.nupkg"

  deploy:
    provider: NuGet
    api_key:
      secure: IHVAasaX8yvwCHeCI/mBgWBRzLNlOpRn3yJnZFyslzTnJpELyxKDaKM5y/LN0zsl
      skip_symbols: false
      artifact: /.*\.nupkg/